### ISSUE TITLE
refactoring nonlinear equations

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/temfpy#33]
Let's discuss the following changes in our call on Wednesday.

- [ ] return only function value and add the analytical jacobian if new optional argument `jac=True`.
- [ ] move equality test between numerical and analytical jacobian to `test_nonlinear_equations.py`
- [ ] doctests only ensure that they evaluate to zero at a random dimension of the problem
- [ ] add some motivating notes to the functions if possible, as we did [here](https://temfpy.readthedocs.io/en/latest/optimization.html)
- [ ] replace `exponential_function` in the lecture on nonlinear equations with the `tempfy`implementation

**Comment by manuhuth** [comment]
- move default values to function header -> tuple
