### ISSUE TITLE
scipy.rosen

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/temfpy#34]
I would like to pass in a simple float as well, right now this throws an error and I need to pass in an array-like type.

**Comment by manuhuth** [comment]
Do you mean just one float as input? Isn't the Rosenbrock function only defined for multidimensional inputs (see [Wikipedia](https://en.wikipedia.org/wiki/Rosenbrock_function)) or is there any other implementation of it for one-dimensional inputs?

Using rosenbrock( [arbitrary float] ) results in 0 at the moment (short test for 100 integers and 100 random normally distributed values). Is zero the desired output for rosenbrock( arbitrary float ) as well?

**Comment by peisenha** [comment]
Yes, you are right, please just add an informative error message when passing in a single variable.

---

Philipp Eisenhauer
Economist

Mail [peisenha@protonmail.com](mailto:eisenhauer@policy-lab.org)
Web https://peisenha.github.io
Repository https://github.com/peisenha

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by manuhuth** [comment]
Done.
